<template>
  <div class="reports-page">
    <div class="report-card">
      <div class="card-header">
        <div>
          <h3 class="card-title">Common Space Reports</h3>
          <p class="card-subtitle">Generate a stream-level summary for any active source that includes the `common_space` task.</p>
        </div>
        <button class="btn-secondary" @click="fetchStreams" :disabled="streamsLoading">
          {{ streamsLoading ? 'Refreshing...' : 'Refresh Streams' }}
        </button>
      </div>

      <div v-if="streamsError" class="state-error">{{ streamsError }}</div>
      <div v-else-if="streamsLoading && streams.length === 0" class="state-msg">Loading available streams...</div>
      <div v-else-if="streams.length === 0" class="state-msg">No active streams with Common Space analysis.</div>

      <template v-else>
        <div class="controls-grid">
          <div class="form-row">
            <label class="form-label">Stream</label>
            <select v-model="selectedStreamId" class="form-input">
              <option v-for="stream in streams" :key="stream.stream_id" :value="stream.stream_id">
                {{ stream.stream_id }} | {{ stream.camera_id || '-' }} | {{ stream.url }}
              </option>
            </select>
          </div>

          <div class="form-row">
            <label class="form-label">Time Range</label>
            <select v-model.number="rangeSeconds" class="form-input">
              <option :value="1800">Last 30 Minutes</option>
              <option :value="7200">Last 2 Hours</option>
              <option :value="86400">Last 24 Hours</option>
              <option :value="604800">Last 7 Days</option>
            </select>
          </div>
        </div>

        <div v-if="selectedStream" class="stream-meta">
          <div><span class="meta-label">Camera</span><span>{{ selectedStream.camera_id || '-' }}</span></div>
          <div><span class="meta-label">Location</span><span>{{ selectedStream.location || '-' }}</span></div>
          <div><span class="meta-label">Coordinates</span><span>{{ selectedStream.lat_lng || '-' }}</span></div>
          <div><span class="meta-label">Status</span><span>{{ selectedStream.status || '-' }}</span></div>
          <div class="meta-url"><span class="meta-label">RTSP URL</span><code>{{ selectedStream.url }}</code></div>
        </div>

        <div class="form-actions">
          <button class="btn-primary" @click="generateReport" :disabled="loading || !selectedStream">
            {{ loading ? 'Generating...' : 'Generate Rule Report' }}
          </button>
          <button class="btn-secondary" @click="generateReport('llm')" :disabled="loading || !selectedStream">
            {{ loading ? 'Generating...' : 'Generate LLM Report' }}
          </button>
        </div>

        <div v-if="reportError" class="state-error">{{ reportError }}</div>
        <div v-else-if="loading" class="state-msg">Generating report...</div>

        <div v-if="report" class="report-result">
          <div class="summary-card">
            <div class="summary-label">Generated Summary</div>
            <p class="summary-text">{{ summaryText }}</p>
            <div class="summary-meta">
              <span>Generated by {{ summarySource }}</span>
              <span>{{ formatTime(report.window.start_time) }} - {{ formatTime(report.window.end_time) }}</span>
              <span v-if="savedReportId">Saved ID {{ savedReportId }}</span>
            </div>
          </div>

          <div class="stats-grid">
            <div class="stat-item">
              <span class="stat-label">Events</span>
              <span class="stat-value">{{ report.window.event_count }}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Dominant Occupancy</span>
              <span class="stat-value">{{ report.stats.dominant_occupancy }}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Avg People</span>
              <span class="stat-value">{{ report.stats.avg_people_count }}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Peak People</span>
              <span class="stat-value">{{ report.stats.peak_people_count }}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Safety Events</span>
              <span class="stat-value">{{ report.stats.safety_event_count }}</span>
            </div>
          </div>

          <div class="report-sections">
            <section class="report-section">
              <h4 class="section-title">Occupancy Distribution</h4>
              <div class="pill-list">
                <span v-for="item in occupancyDistribution" :key="item.label" class="pill">
                  {{ item.label }}: {{ item.count }}
                </span>
              </div>
            </section>

            <section class="report-section">
              <h4 class="section-title">Top Activities</h4>
              <div v-if="report.stats.top_activities.length === 0" class="empty-inline">No activity tags available.</div>
              <div v-else class="pill-list">
                <span v-for="item in report.stats.top_activities" :key="item.name" class="pill">
                  {{ formatActivity(item.name) }} · {{ item.count }}
                </span>
              </div>
            </section>

            <section class="report-section">
              <h4 class="section-title">Highlights</h4>
              <div v-if="highlightItems.length === 0" class="empty-inline">No highlight text available.</div>
              <p v-for="item in highlightItems" :key="item" class="highlight-text">{{ item }}</p>
            </section>

            <section class="report-section">
              <h4 class="section-title">Recent Sample Events</h4>
              <div v-if="report.sample_events.length === 0" class="empty-inline">No events in the selected window.</div>
              <div v-else class="sample-list">
                <article v-for="(event, idx) in report.sample_events" :key="event.timestamp || idx" class="sample-item">
                  <div class="sample-head">
                    <span class="sample-time">{{ formatTime(event.timestamp) }}</span>
                    <span class="sample-occupancy">{{ event.analysis_summary?.space_occupancy || 'unknown' }}</span>
                  </div>
                  <p class="sample-desc">{{ event.description || 'No description' }}</p>
                  <p v-if="event.analysis_summary?.scene_summary" class="sample-note">{{ event.analysis_summary.scene_summary }}</p>
                </article>
              </div>
            </section>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'

const API = 'http://localhost:5000'

const streams = ref([])
const selectedStreamId = ref('')
const rangeSeconds = ref(7200)
const report = ref(null)
const summaryText = ref('')
const summarySource = ref('')
const savedReportId = ref('')
const loading = ref(false)
const streamsLoading = ref(false)
const streamsError = ref('')
const reportError = ref('')

const selectedStream = computed(() =>
  streams.value.find(stream => stream.stream_id === selectedStreamId.value) || null
)

const occupancyDistribution = computed(() => {
  const distribution = report.value?.stats?.occupancy_distribution || {}
  return [
    { label: 'Low', count: distribution.low || 0 },
    { label: 'Medium', count: distribution.medium || 0 },
    { label: 'High', count: distribution.high || 0 },
    { label: 'Unknown', count: distribution.unknown || 0 },
  ]
})

const highlightItems = computed(() => {
  if (!report.value) return []
  return [
    ...(report.value.highlights?.scene_summaries || []),
    ...(report.value.highlights?.occupancy_reasons || []),
  ]
})

function formatTime(ts) {
  if (!ts) return '-'
  return new Date(ts * 1000).toLocaleString('en-US', {
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function formatActivity(name) {
  return String(name || '-').replace(/_/g, ' ')
}

async function fetchStreams() {
  streamsLoading.value = true
  streamsError.value = ''

  try {
    const res = await fetch(`${API}/api/reports/common-space/streams`)
    const data = await res.json()
    if (!res.ok || !data.success) {
      throw new Error(data.error || 'Failed to fetch report streams')
    }

    const nextStreams = data.items || []
    streams.value = nextStreams

    if (!nextStreams.some(stream => stream.stream_id === selectedStreamId.value)) {
      selectedStreamId.value = nextStreams[0]?.stream_id || ''
    }
  } catch (error) {
    streamsError.value = error.message || 'Failed to fetch report streams'
  } finally {
    streamsLoading.value = false
  }
}

async function generateReport(mode = 'rule') {
  if (!selectedStream.value) return

  loading.value = true
  reportError.value = ''
  report.value = null
  summaryText.value = ''
  summarySource.value = ''
  savedReportId.value = ''

  try {
    const endTime = Math.floor(Date.now() / 1000)
    const startTime = endTime - Number(rangeSeconds.value)

    const endpoint = mode === 'llm'
      ? `${API}/api/reports/common-space/generate-llm`
      : `${API}/api/reports/common-space/generate`

    const res = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        stream_id: selectedStream.value.stream_id,
        url: selectedStream.value.url,
        start_time: startTime,
        end_time: endTime,
        language: 'zh-CN',
      }),
    })
    const data = await res.json()
    if (!res.ok || !data.success) {
      throw new Error(data.error || 'Failed to generate report')
    }

    report.value = data.report
    summaryText.value = data.llm_summary || data.report?.narrative || ''
    summarySource.value = data.llm_meta?.model || data.report?.generated_by || 'unknown'
    savedReportId.value = data.saved_report_id || ''
  } catch (error) {
    reportError.value = error.message || 'Failed to generate report'
  } finally {
    loading.value = false
  }
}

onMounted(fetchStreams)
</script>

<style scoped>
.reports-page {
  max-width: 1120px;
}

.report-card {
  background: var(--color-bg-secondary);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  padding: 22px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
  margin-bottom: 20px;
}

.card-title {
  font-size: 18px;
  font-weight: 600;
  margin-bottom: 6px;
}

.card-subtitle {
  font-size: 13px;
  color: var(--color-text-muted);
  line-height: 1.5;
}

.controls-grid {
  display: grid;
  grid-template-columns: minmax(280px, 2fr) minmax(180px, 1fr);
  gap: 16px;
  margin-bottom: 16px;
}

.form-row {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.form-label {
  font-size: 13px;
  color: var(--color-text-secondary);
}

.form-input {
  width: 100%;
  padding: 10px 12px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--color-border);
  background: var(--color-bg-primary);
}

.stream-meta {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
  padding: 14px;
  margin-bottom: 16px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-sm);
  background: var(--color-bg-tertiary);
}

.meta-label {
  display: block;
  margin-bottom: 4px;
  font-size: 12px;
  color: var(--color-text-muted);
}

.meta-url {
  grid-column: 1 / -1;
}

.meta-url code {
  display: block;
  white-space: normal;
  word-break: break-word;
}

.form-actions {
  display: flex;
  gap: 10px;
  margin-bottom: 18px;
}

.btn-primary,
.btn-secondary {
  padding: 10px 14px;
  border-radius: var(--radius-sm);
  font-size: 13px;
  font-weight: 600;
}

.btn-primary {
  background: var(--color-accent);
  color: #fff;
}

.btn-primary:hover:not(:disabled) {
  background: var(--color-accent-hover);
}

.btn-secondary {
  background: var(--color-bg-tertiary);
  color: var(--color-text-primary);
  border: 1px solid var(--color-border);
}

.btn-secondary:hover:not(:disabled) {
  background: var(--color-bg-primary);
}

.btn-primary:disabled,
.btn-secondary:disabled {
  cursor: default;
  opacity: 0.7;
}

.state-msg,
.state-error {
  padding: 12px 14px;
  border-radius: var(--radius-sm);
  font-size: 13px;
}

.state-msg {
  background: var(--color-bg-tertiary);
  color: var(--color-text-secondary);
}

.state-error {
  background: rgba(239, 68, 68, 0.1);
  border: 1px solid rgba(239, 68, 68, 0.25);
  color: var(--color-danger);
  margin-bottom: 16px;
}

.report-result {
  display: flex;
  flex-direction: column;
  gap: 18px;
}

.summary-card {
  padding: 18px;
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, rgba(34, 197, 94, 0.12), rgba(59, 130, 246, 0.08));
  border: 1px solid rgba(34, 197, 94, 0.18);
}

.summary-label {
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--color-success);
}

.summary-text {
  margin-top: 10px;
  font-size: 15px;
  line-height: 1.7;
  color: var(--color-text-primary);
}

.summary-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 12px;
  font-size: 12px;
  color: var(--color-text-muted);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(5, minmax(0, 1fr));
  gap: 12px;
}

.stat-item {
  padding: 14px;
  border-radius: var(--radius-sm);
  background: var(--color-bg-tertiary);
  border: 1px solid var(--color-border);
}

.stat-label {
  display: block;
  font-size: 12px;
  color: var(--color-text-muted);
  margin-bottom: 8px;
}

.stat-value {
  font-size: 18px;
  font-weight: 700;
  color: var(--color-text-primary);
}

.report-sections {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 16px;
}

.report-section {
  padding: 16px;
  border-radius: var(--radius-md);
  background: var(--color-bg-tertiary);
  border: 1px solid var(--color-border);
}

.section-title {
  font-size: 14px;
  font-weight: 600;
  margin-bottom: 12px;
}

.pill-list {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.pill {
  padding: 6px 10px;
  border-radius: 999px;
  background: rgba(59, 130, 246, 0.12);
  color: var(--color-accent);
  font-size: 12px;
  font-weight: 600;
}

.highlight-text,
.sample-desc,
.sample-note,
.empty-inline {
  font-size: 13px;
  line-height: 1.6;
  color: var(--color-text-secondary);
}

.highlight-text + .highlight-text {
  margin-top: 8px;
}

.sample-list {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.sample-item {
  padding: 12px;
  border-radius: var(--radius-sm);
  background: var(--color-bg-primary);
  border: 1px solid var(--color-border);
}

.sample-head {
  display: flex;
  justify-content: space-between;
  gap: 10px;
  margin-bottom: 8px;
  font-size: 12px;
  color: var(--color-text-muted);
}

.sample-occupancy {
  text-transform: capitalize;
}

.sample-note {
  margin-top: 6px;
  color: var(--color-text-muted);
}

@media (max-width: 960px) {
  .controls-grid,
  .stats-grid,
  .report-sections,
  .stream-meta {
    grid-template-columns: 1fr;
  }

  .card-header {
    flex-direction: column;
  }
}
</style>
